In [1]:
import numpy as np
import pandas as pd
import statistics
import scipy.stats

# 1. Medidas de tendencia central


## 1.1 Promedio
Imaginemos que queremos estudiar la altura de un curso.

In [49]:
estaturas_1 = [1.60, 1.63, 1.68, 1.69, 1.70, 1.72, 1.72, 1.73, 1.74, 1.76, 1.78, 1.81, 1.83, 1.84, 1.85]
np.ptp(estaturas_1) # Diferencia entre maximo y minimo

0.25

In [50]:
len(estaturas_1)

15

In [3]:
# calculamos en la forma clásica
sum(estaturas_1)/len(estaturas_1)

1.7386666666666666

In [4]:
# usamos la función especifica
np.mean(estaturas_1)

1.7386666666666668

Agregamos un jugador de basquet para ver la sensibilidad a outliers.

In [5]:
estaturas_2 = [1.60, 1.63, 1.68, 1.69, 1.70, 1.72, 1.72, 1.73, 1.74, 1.76, 1.78, 1.81, 1.83, 1.84, 1.85, 2.19]
np.mean(estaturas_2)

1.766875

Vemos que pasa cuando agregamos faltantes

In [6]:
estaturas_faltantes = estaturas_1 + [np.nan]
np.mean(estaturas_faltantes)

nan

In [7]:
# usamos la función nanmean() para resolver el problema
np.nanmean(estaturas_faltantes, )

1.7386666666666666

## 1.2 Mediana
Vamos a hacer un análisis similar al que hicimos con el promedio

In [8]:
# Calculemos cuantos elementos tiene nuestra variable
observaciones_estaturas_1 = len(estaturas_1)
observaciones_estaturas_1

15

In [9]:
# Tenemos 15 elementos (es una cantidad impar), busquemos en que posicion se encuentra la mediana
posicion_mediana_estatura_1 = int((observaciones_estaturas_1 + 1)/2 - 1)# resta 1 por el indice
posicion_mediana_estatura_1

7

In [12]:
# La mediana esta en la posicion 7# Mediana de la variable estatura_2
np.median(estaturas_2) #(que recordemos que es la 8va), como nuestro vector ya esta ordenado de menor a mayor accedemos al dato en esa posicion
mediana_estaturas_1 = estaturas_1[posicion_mediana_estatura_1]
mediana_estaturas_1

1.73

In [13]:
# Mediana de la variable estatura_2 (con outlier)
round(np.median(estaturas_2),2)

1.74

## 1.3 Moda

In [14]:
#estaturas_1

In [15]:
moda = max((estaturas_1.count(item), item) for item in set(estaturas_1))[1]
moda

1.72

In [16]:
moda = statistics.mode(estaturas_1)
print(moda)

1.72


In [51]:
# La funcióón para calcular modas multiples se incorpora en Python 3.8

moda = statistics.multimode(estaturas_1)
print(moda)

[1.72]


# 2. Medidas de posición

## 2.1 Máximo y mínimo

In [18]:
# Maximo de la variable estaturas_1
maximo_estaturas_1 = max(estaturas_1)
print(maximo_estaturas_1)
# Maximo de la variable estaturas_2
maximo_estaturas_2 = max(estaturas_2)
print(maximo_estaturas_2)

1.85
2.19


In [19]:
# Minimo de la variable estaturas_1
minimo_estaturas_1 = min(estaturas_1)
print(minimo_estaturas_1)
# Minimo de la variable estaturas_2
minimo_estaturas_2 = min(estaturas_2)
print(minimo_estaturas_2)

1.6
1.6


## 2.2 Cuantiles

In [20]:
# Calculamos el primer cuartil de estaturas 1. Entonces indicamos que deben quedar 25% de los datos a izquierda.
np.quantile(estaturas_1, 0.25)

1.6949999999999998

In [21]:
# Calculamos el primer cuartil de estaturas 2. Entonces indicamos que deben quedar 25% de los datos a izquierda.
np.quantile(estaturas_2, 0.25)

1.6975

In [22]:
# Calculamos el septimo decil de estaturas 2. Entonces indicamos que deben quedar 70% de los datos a izquierda.
np.quantile(estaturas_2, 0.70)

1.795

In [23]:
# Calculamos todos los cuartiles
np.quantile(estaturas_1, [0.25, 0.5, 0.75])

array([1.695, 1.73 , 1.795])

# 3. Medidas de dispersión


## 3.1 Rango

In [24]:
# Calculamos el rango de estaturas 1
rango_estaturas_1 = maximo_estaturas_1 - minimo_estaturas_1
rango_estaturas_1

0.25

In [25]:
# Calculamos el rango de estaturas 2
rango_estaturas_2 = maximo_estaturas_2 - minimo_estaturas_2
rango_estaturas_2

0.5899999999999999

In [26]:
# Usamos la funcion específica
np.ptp(estaturas_1)

0.25

OBS: esta función no funciona con datos faltantes si se los pasamos como un NumPy array, pero si lo hará si usamos un objeto con formato de Pandas Series.

## 3.2 Varianza

In [27]:
# Calculamos la varianza usando la fórmula
n = len(estaturas_1)
mean_ = sum(estaturas_1) / n
var_ = sum((item - mean_)**2 for item in estaturas_1) / (n - 1)
round(var_,4)

0.0055

In [28]:
# Ahora, usando la función especifica
var_ = statistics.variance(estaturas_1)
round(var_,4)

0.0055

In [29]:
# También podemos usar numpy
var_ = np.var(estaturas_1)
round(var_,4)

0.0052

En caso de tener datos faltantes, es recomendable usar la función ``np.nanvar()` porque los otros casos no funcionarán.

## 3.3 Desvío estándar

In [30]:
# Calculamos usando la formula
std_ = var_ ** 0.5
std_

0.07182076456166578

In [31]:
# Ahora usando la funcion especifica
std_ = statistics.stdev(estaturas_1)
std_

0.07434155410446214

In [32]:
# Tambien numpy tiene una funcion
np.std(estaturas_1)

0.07182076456166578

## 3.4 Asimetría

In [33]:
# Vamos a calcular la asimetría usando la formula completa
x = [8.0, 1, 2.5, 4, 28.0]
n = len(x)
mean_ = sum(x) / n
var_ = sum((item - mean_)**2 for item in x) / (n - 1)
std_ = var_ ** 0.5
skew_ = (sum((item - mean_)**3 for item in x) * n / ((n - 1) * (n - 2) * std_**3))
skew_

1.947043227390592

Vemos que el resultado es positivo, por lo tanto x tiene una cola a derecha.

In [52]:
# Ahora vamos a usar la funcion especifica
scipy.stats.skew(x,bias=False) # bias , tiene que ver con el grado de libertad

0.0

La funcion tiene parametros adicionales para indicar como trabajar con datos faltantes y para implementar correcciones al sesgo: 
[link a la documentación](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.skew.html)



# 4. Medidas de relación entre variables




## 4.1 Correlación

In [35]:
# Vamos a generar dos variables para analizar luego
x = list(range(-10, 11))
y = [0, 2, 2, 2, 2, 3, 3, 6, 7, 4, 7, 6, 6, 9, 4, 5, 5, 10, 11, 12, 14]
x_, y_ = np.array(x), np.array(y)
x__, y__ = pd.Series(x_), pd.Series(y_)


### 4.1.1 Covarianza

In [36]:
# Calculamos la covarianza usando la fórmula
n = len(x)
mean_x, mean_y = sum(x) / n, sum(y) / n
cov_xy = (sum((x[k] - mean_x) * (y[k] - mean_y) for k in range(n)) / (n - 1))
cov_xy

19.95

Vamos a calcular la **matriz de covarianza** entre variables. Aquí vemos la covarianza de todas las variables con todas las variables.

In [37]:
cov_matrix = np.cov(x_, y_)
cov_matrix

array([[38.5       , 19.95      ],
       [19.95      , 13.91428571]])

Vemos que la covarianza que nos interesa aparece en la esquina superior derecha (`cov_matrix[0, 1]`) y en la esquina inferior izquierda (`cov_matrix[1, 0]`) ya que se corresponden ambas a la covarianza entre x e y. 

La covarianza de la esquina superiror izquierda (`cov_matrix[0, 0]`) corresponde a la covarianza entre x y x y la inferior derecha (`cov_matrix[1, 1]`) a la covarianza entre y e y. Notese que la covarianza entre una variabe y ella misma es en definitiva la varianza de la variable.

In [38]:
# Podemos calcular directamente las covarianzas entre dos variables
cov_xy = x__.cov(y__)
print(cov_xy)
cov_xy = y__.cov(x__)
print(cov_xy)

19.950000000000003
19.950000000000003


### 4.1.2 Coeficiente de correlación

In [39]:
# Vamos a calcularlo usando la fórmula
var_x = sum((item - mean_x)**2 for item in x) / (n - 1)
var_y = sum((item - mean_y)**2 for item in y) / (n - 1)
std_x, std_y = var_x ** 0.5, var_y ** 0.5
r = cov_xy / (std_x * std_y)
r

0.861950005631606

In [40]:
# Vamos a usar la funcion de scipy
r, p = scipy.stats.pearsonr(x_, y_)
print(r)
print(p)

0.8619500056316061
5.122760847201142e-07


Esta función nos devuelve el coeficiente de correlación (*r*) junto con su p-valor (*p*).

Numpy tiene una matriz de correlación que simplemente nos devuelve los coeficientes de correlación. Su interpretación es análoga a la de la matriz de covarianzas.


In [41]:
corr_matrix = np.corrcoef(x_, y_)
corr_matrix

array([[1.        , 0.86195001],
       [0.86195001, 1.        ]])

También podemos usar la función de Pandas para 

In [55]:
y__.corr(x__) 


0.8619500056316062

También podríamos usar una regresión lineal para calcular el coeficiente de correlación.

In [44]:
result = scipy.stats.linregress(x_, y_)
r = result.rvalue
r

0.8619500056316061

# 5. Ejercicio *huertas*

Trabajaremos con un conjunto de datos del portal de datos abiertos de Argentina. Es un dataset que contiene información sobre el programa ProHuerta para febrero de 2019 

In [45]:
huertas = pd.read_csv('dahuertas2.csv', sep = ';', encoding = 'latin-1')
huertas.head()

PERIODO  ID PROVINCIA     PROVINCIA ID DEPARTAMENTO  \
0  2019-02-01             6  BUENOS AIRES           06854   
1  2019-02-01             6  BUENOS AIRES           06588   
2  2019-02-01             6  BUENOS AIRES           06007   
3  2019-02-01             6  BUENOS AIRES           06014   
4  2019-02-01             6  BUENOS AIRES           06021   

             DEPARTAMENTO  HUERTAS FAMILIARES  HUERTAS ESCOLARES  \
0              25 DE MAYO                 988                 44   
1              9 DE JULIO                   0                 13   
2           ADOLFO ALSINA                 333                 32   
3  ADOLFO GONZALES CHAVES                 197                 13   
4                 ALBERTI                 318                 16   

   HUERTAS COMUNITARIAS E INSTITUCIONALES  
0                                       3  
1                                       0  
2                                      12  
3                                       1  
4                                       0

Vemos que tenemos 8 variables y 516 observaciones. Tenemos informacion de la provincia, el departamento, la cantidad de huertas familiares, escolares y comunitarias e institucionales.

Cada observacion es un departamento en Argentina

## 5.1 Medidas de resumen generales

Supongamos que estamos somos un grupo de analistas que nos interesa analizar el comportamiento de la variable huertas escolares. Vamos a extraer algunas métricas de interés sobre nuestro dataset.

In [46]:
v_huertas_escolares = huertas['HUERTAS ESCOLARES'].to_list()

print("Tenemos un total de {} huertas escolares.".format(sum(v_huertas_escolares)))
print("Con una media de {} huertas escolares y una mediana de {}.".format(round(np.mean(v_huertas_escolares), 2), round(np.median(v_huertas_escolares),2)))
print("El departamento con mayor cantidad de huertas tiene {}  y el  que menos tiene {}.".format(max(huertas['HUERTAS ESCOLARES']), min(huertas['HUERTAS ESCOLARES'])))
print("Tenemos una varianza de {} huertas.".format(round(np.var(v_huertas_escolares),2)))


Tenemos un total de 14403 huertas escolares.
Con una media de 27.91 huertas escolares y una mediana de 20.0.
El departamento con mayor cantidad de huertas tiene 211  y el  que menos tiene 0.
Tenemos una varianza de 747.71 huertas.


## 5.2 Medidas de resumen por provincia

Ahora queremos profundizar en nuestro análisis y calcular las medidas de resumen anteriores para cada provincia:

In [47]:
huertas['HUERTAS ESCOLARES'].fillna(0, inplace = True)

huertas_gr = huertas.groupby('PROVINCIA').agg({'DEPARTAMENTO': 'count', 
                         'HUERTAS ESCOLARES': ['mean', 'min', 'max', 'var']})
huertas_gr.head()
#huertas_gr.columns = ['DEPARTAMENTO', 'cant_dptos', 'promedio_huertas', 'min_huertas', 'max_huertas', 'varianza']

C:\Users\carlos\AppData\Local\Temp\ipykernel_3300\3966776895.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  huertas['HUERTAS ESCOLARES'].fillna(0, inplace = True)


DEPARTAMENTO HUERTAS ESCOLARES                      
                       count              mean min  max          var
PROVINCIA                                                           
BUENOS AIRES             128         17.023438   0   53   160.621494
CAPITAL FEDERAL            1         75.000000  75   75          NaN
CATAMARCA                 17         14.000000   0   27    68.750000
CHACO                     26         75.807692   0  148  1134.881538
CHUBUT                    14          9.571429   0   32    91.494505

Ahora podemos contestar las siguientes preguntas:

*    ¿Cuáles son las 3 provincias con mayor cantidad de huertas escolares? ¿Y las 3 con menor cantidad?
*    ¿Cuál es la provincia qué, en promedio, tiene mayor cantidad de huertas? ¿Y la que menos tiene?
*    ¿Qué provincia tiene el distrito con mayor cantidad de huertas escolares?
*    ¿Cuáles provincias no tienen distritos sin huertas escolares?
